name = "storycharts"
compatibility_date = "2024-01-01"
pages_build_output_dir = "www"

[[d1_databases]]
binding = "DB"
database_name = "storycharts"
database_id = "41752f86-e530-461e-aaa9-838c27b00e89"
